import { z } from 'zod';
import { and, eq } from 'drizzle-orm';
import { agents, contractVersions, contracts, db } from '@/lib/db';
import { fetchForReading } from '@/lib/integrations/drive';
import { ask } from '@/lib/integrations/claude';
import { writeAudit } from '@/lib/audit';

/**
 * Answering a contract: what to change, and the mail that says so.
 *
 * This is the step between reading a draft and sending it back. It proposes
 * the edits, shows each one against the clause it replaces, and drafts the
 * covering email. What it never does is rewrite the document — a contract
 * regenerated by a model is a contract nobody can diff against the one they
 * sent, and the formatting, numbering and defined terms all move. The
 * counterparty gets his words in an email and, if he wants it, a clean list of
 * changes filed beside the draft in Drive.
 *
 * His standing positions live in the contract-redliner agent's brief, so the
 * same instructions drive this button and the agent when he switches it on:
 * one place to teach, whichever way it runs.
 *
 * Nothing here sends anything. §6.1 makes sending an external document
 * irreversible, so the send stays a click he makes, with the draft in front
 * of him.
 */

export const redlineSchema = z.object({
  /** One line: what this document is and how bad it is. */
  verdict: z.string(),
  /** Whether it is close enough to sign as-is. */
  signable: z.boolean(),
  changes: z.array(
    z.object({
      clause: z.string(),
      /** The text as it stands, quoted from the document. */
      original: z.string(),
      /** What to put in its place. */
      proposed: z.string(),
      why: z.string(),
      severity: z.enum(['blocking', 'important', 'minor']),
    }),
  ),
  additions: z.array(
    z.object({ clause: z.string(), text: z.string(), why: z.string() }),
  ),
  /** Things worth asking about rather than redrafting. */
  questions: z.array(z.string()),
  email: z.object({ subject: z.string(), body: z.string() }),
});

export type Redline = z.infer<typeof redlineSchema>;

const SYSTEM = `You are preparing the reply to a contract draft on behalf of
Maor Davidovich, CEO of Adnimation, an Israeli ad-tech company that both buys
demand and sells supply.

Your job is to say what to change and to write the covering email. You are not
redrafting the document and you are not giving legal advice.

For every change: quote the clause as it actually stands in "original" — never
paraphrase it, because he will compare your quote against the document — and
put the replacement wording in "proposed". Wording, not instructions: what he
sends back has to be usable as-is.

Rank honestly. "blocking" is for terms that must change before signing —
uncapped liability, exclusivity he has not agreed, auto-renewal with a long
notice, payment terms beyond 60 days, unilateral rate changes, IP assignment,
personal guarantees. "important" is worth pushing on. "minor" is tidying. If
the draft is genuinely fine, say so, return few or no changes, and set
"signable" true rather than inventing objections to look useful.

The email is from him to the counterparty: short, plain, warm enough to keep
the deal moving, listing the substantive points and not the minor ones. No
legal threats, no deadlines he has not given you, and never a figure that is
not already in the document or in his instructions. Write it in the language
the counterparty is likely to read — English unless the document is Hebrew.`;

const PROMPT = `Read this contract and prepare the reply. Answer as JSON:

{
  "verdict": "one line — what this is and how far it is from signable",
  "signable": false,
  "changes": [{
    "clause": "the clause number or name",
    "original": "the text exactly as it stands",
    "proposed": "the wording to put in its place",
    "why": "one line, in his interest",
    "severity": "blocking|important|minor"
  }],
  "additions": [{ "clause": "what to add", "text": "the wording", "why": "one line" }],
  "questions": ["anything to ask rather than redraft"],
  "email": { "subject": "…", "body": "the covering email, ready to send" }
}

Return only the JSON.`;

export interface RedlineResult {
  ok: boolean;
  redline?: Redline;
  error?: string;
  needsKey?: boolean;
  versionNo?: number;
  fileName?: string;
  versionId?: string;
  /** True when his standing positions were included. */
  usedBrief?: boolean;
  /**
   * Their draft as text, so the screen can show it beside our changes with the
   * problem passages marked. Absent for a scanned PDF Drive cannot convert —
   * the review still works, it just cannot highlight inside the document.
   */
  documentText?: string;
}

/** His standing positions, from the contract-redliner agent's brief. */
export async function redlineBrief(): Promise<string> {
  const [agent] = await db
    .select({ instructions: agents.instructions })
    .from(agents)
    .where(eq(agents.name, 'contract-redliner'))
    .limit(1);
  return (agent?.instructions ?? '').trim();
}

export async function redlineContract(
  contractId: string,
  versionId?: string,
): Promise<RedlineResult> {
  const [contract] = await db
    .select()
    .from(contracts)
    .where(eq(contracts.id, contractId))
    .limit(1);
  if (!contract) return { ok: false, error: 'No such contract' };

  const versions = await db
    .select()
    .from(contractVersions)
    .where(
      versionId
        ? and(eq(contractVersions.contractId, contractId), eq(contractVersions.id, versionId))
        : eq(contractVersions.contractId, contractId),
    );

  // A named document, or the newest — an email often carries three at once,
  // and each is answered on its own terms.
  const target = versions
    .filter((v) => v.driveFileId)
    .sort((a, b) => b.versionNo - a.versionNo)[0];

  if (!target?.driveFileId) {
    return { ok: false, error: versionId ? 'That document is not in Drive' : 'Nothing to read yet' };
  }

  const file = await fetchForReading(target.driveFileId);
  if (!file.ok) return { ok: false, error: file.error };

  const brief = await redlineBrief();
  const preamble = [
    `The counterparty is ${contract.counterpartyName}.`,
    contract.category && contract.categoryConfirmed
      ? `We treat them as ${contract.category}.`
      : '',
    brief
      ? `Maor's standing positions, which override anything above where they are stricter:\n${brief}`
      : '',
  ]
    .filter(Boolean)
    .join('\n\n');

  const prompt = `${preamble}\n\n${PROMPT}`;

  const result =
    file.kind === 'pdf'
      ? await ask<Redline>(prompt, {
          system: SYSTEM,
          document: { base64: file.base64, mediaType: 'application/pdf' },
          schema: redlineSchema,
          maxTokens: 6000,
        })
      : await ask<Redline>(`${prompt}\n\nThe contract:\n\n${file.text.slice(0, 180_000)}`, {
          system: SYSTEM,
          schema: redlineSchema,
          maxTokens: 6000,
        });

  if (!result.ok) {
    return { ok: false, error: result.error, ...(result.needsKey ? { needsKey: true } : {}) };
  }
  if (!result.parsed) return { ok: false, error: 'Claude did not return a reply' };

  // Capped: a hundred-page schedule is not what he is reading on this screen,
  // and the whole thing has to cross the wire to the browser.
  const documentText =
    file.kind === 'text' ? file.text : (file.text ?? '');

  return {
    ok: true,
    redline: result.parsed,
    versionNo: target.versionNo,
    fileName: target.fileName,
    versionId: target.id,
    usedBrief: brief.length > 0,
    ...(documentText.trim() ? { documentText: documentText.slice(0, 120_000) } : {}),
  };
}

/**
 * One clause, redrafted the way he just said.
 *
 * The proposal is a starting point; what he actually wants is usually one
 * degree different — "make it net 45, not 30", "we can live with exclusivity
 * if there is a minimum". This takes that sentence and turns it into wording
 * he can send, without re-reading the whole contract to do it.
 */
export const rewordSchema = z.object({
  proposed: z.string(),
  why: z.string(),
});

export async function rewordClause(input: {
  counterparty: string;
  clause: string;
  original: string;
  currentProposal: string;
  instruction: string;
}): Promise<{ ok: true; proposed: string; why: string } | { ok: false; error: string }> {
  const brief = await redlineBrief();

  const result = await ask<{ proposed: string; why: string }>(
    [
      `Counterparty: ${input.counterparty}`,
      `Clause: ${input.clause}`,
      `As it stands in their draft:\n${input.original}`,
      `What we were going to send back:\n${input.currentProposal}`,
      `What Maor wants instead:\n${input.instruction}`,
      brief ? `His standing positions:\n${brief}` : '',
      '',
      'Rewrite the clause as he wants it. Answer as JSON:',
      '{ "proposed": "the wording to send", "why": "one line for him" }',
    ]
      .filter(Boolean)
      .join('\n\n'),
    {
      system:
        'You redraft one contract clause at a time, for the CEO of Adnimation. ' +
        'Return contract wording, not a description of it — what you write is what gets ' +
        'sent. Keep the drafting style of the document it belongs to, keep defined terms ' +
        'exactly as the document defines them, and change only what he asked to change. ' +
        'If what he asks for is unclear, write the closest defensible wording and say in ' +
        '"why" what you assumed.',
      schema: rewordSchema,
      maxTokens: 1200,
    },
  );

  if (!result.ok) return { ok: false, error: result.error };
  if (!result.parsed) return { ok: false, error: 'Claude did not return wording' };
  return { ok: true, proposed: result.parsed.proposed, why: result.parsed.why };
}

/**
 * Teach the redliner what he just decided.
 *
 * A correction he makes once should not be a correction he makes every time.
 * This appends it to the agent's brief — the same brief that drives both the
 * button and the agent — so the next contract arrives with that position
 * already taken. Appended rather than rewritten: his own words stay his, and
 * nothing he wrote is ever replaced by something inferred from one clause.
 */
export async function rememberPosition(
  position: string,
  actor: string,
): Promise<{ ok: true; brief: string } | { ok: false; error: string }> {
  const line = position.trim().replace(/\s+/g, ' ');
  if (line === '') return { ok: false, error: 'Nothing to remember' };
  if (line.length > 500) return { ok: false, error: 'That is longer than a position should be' };

  const [agent] = await db
    .select({ id: agents.id, instructions: agents.instructions })
    .from(agents)
    .where(eq(agents.name, 'contract-redliner'))
    .limit(1);
  if (!agent) return { ok: false, error: 'The contract redliner is not installed' };

  const existing = (agent.instructions ?? '').trim();
  if (existing.includes(line)) return { ok: true, brief: existing };

  const brief = existing ? `${existing}\n· ${line}` : `· ${line}`;

  await db
    .update(agents)
    .set({ instructions: brief, instructionsUpdatedAt: new Date() })
    .where(eq(agents.id, agent.id));

  await writeAudit({
    actor,
    action: 'agent.instructions',
    entityType: 'agent',
    entityId: agent.id,
    after: { added: line, from: 'contract review' },
  });

  return { ok: true, brief };
}
